CREATE TABLE [dbo].[BlogPost]
(
	[Id] BIGINT NOT NULL PRIMARY KEY NONCLUSTERED IDENTITY, 
	[Title] VARCHAR(100) NOT NULL, 
	[Extract] VARCHAR(200) NULL, 
	[Content] NTEXT NOT NULL, 
	[BlogId] BIGINT NOT NULL, 
	[CreateAt] DATETIMEOFFSET NOT NULL, 
	[CreateBy] BIGINT NOT NULL,
	[ModifyAt] DATETIMEOFFSET NULL,
	[ModifyBy] BIGINT NULL
	CONSTRAINT [FK_BlogPost_ToBlog] FOREIGN KEY ([BlogId]) REFERENCES [Blog]([Id])
)

GO

CREATE CLUSTERED INDEX [IX_BlogPost_BlogId] ON [dbo].[BlogPost] ([BlogId])
